markdown: kramdown
style: modern

# Site settings
title: Jinhang Jiang
description: Data Scientist & Researcher
url: "http://jinhangjiang.com"
baseurl: ""

# Build settings
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Google Analytics
google_analytics: G-DRC2GHV21Q

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jinhang Jiang"
